- hosts: check1
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest

  - name: enable service httpd and ensure it is not masked
    systemd:
      name: httpd
      enabled: yes

